### ISSUE TITLE
Serial port not initialized

### ISSUE THREAD

**Issue by artelse** [benkrasnow/EL_driver_multi#2]
Trying out the Arduino matrix code on a Trinket M0. It compiles fine, code uploads, but then get an error that the serial port (/dev/ttyACM0) isn't initialized. Any hints?
Edit: I did see your comment:
`//Don't forget that this MCU is also running a USB ISR if loaded normally through the Arduino IDE as an Adafruit Trinket M0.  This uses some CPU time, but also allows serial communication for new features or debugging.`
So serial should work?
I noticed the omission of mandatory `Serial.begin(baudrate);`. But, adding it doesn't fix the problem.

**Comment by benkrasnow** [comment]
Sorry for the delay.  Did you get it working?  Can you run any Trinket M0 examples?  On my Windows computer, I have to select a different COM port for debugging than for programming (it re-initializes when the Trinket boots and establishes a new COM port)

**Comment by artelse** [comment]
Hi, thanks for the feedback. I am able now to upload a simple serial port program and this works (see code below if someone wants to test).
Next step is to get the matrix code tested. Will report back on my results.
```
// UF2 Bootloader v1.23.0 SFHR
// Model: Trinket M0
// Board-ID: SAMD21E18A-Trinket-v0

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(13, OUTPUT);
  Serial.begin(9600);
}
// the loop function runs over and over again forever
void loop() {
  Serial.println("hello");
  digitalWrite(13, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);              // wait for a second
  digitalWrite(13, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);              // wait for a second
}
```

**Comment by artelse** [comment]
Haven't found a fix yet, but when I disable `NVIC_EnableIRQ(TCC2_IRQn);`, the serial port works. I also swapped with the next line to `NVIC_SetPriority(TCC2_IRQn, 0);` because it makes sense to set priority first.
The problem you have with the serial port on Windows is described [here](https://www.avdweb.nl/arduino/samd21/virus). None of these fixes my problem though, so it must have to do something with the timer interrupt?
Can you point me to documentation of register settings, library, etc. as this processor is new to me and want to dig into it more. Thx!

**Comment by artelse** [comment]
Ok, couldn't find why enabling that interrupt locked up the cpu. So loaded the code on a fresh Trinket M0 original board and now it runs just fine. My idea now is that I have damaged the ADC input somehow because I had an issue with the 100:1 voltage divider.
Edit: confirmed, disabling ADC from the interrupt fixes the problem.
